export enum IdentificationTypeDife {
  CITIZENSHIP_CARD = 'CC',
  FOREIGN_ID_CARD = 'CE',
  UNIQUE_PERSONAL_IDENTIFICATION_NUMBER = 'NUIP',
  TEMPORARY_PROTECTION_PERMIT = 'PPT',
  SPECIAL_PERMANENCE_PERMIT = 'PEP',
  PASSPORT = 'PAS',
  IDENTITY_CARD = 'TDI',
  TAX_IDENTIFICATION_NUMBER = 'NIT'
}

export enum KeyStatusDife {
  ACTIVE = 'ACTIVE',
  BLOCKED_BY_PARTICIPANT = 'BLOCKED_PARTICIPANT',
  BLOCKED_BY_CLIENT = 'BLOCKED_CLIENT'
}

export enum KeyTypeDife {
  IDENTIFICATION_NUMBER = 'NRIC',
  MOBILE_NUMBER = 'M',
  EMAIL = 'E',
  ALPHANUMERIC_IDENTIFIER = 'O',
  BUSINESS_CODE = 'B'
}

export enum PaymentMethodTypeDife {
  SAVINGS_ACCOUNT = 'CAHO',
  CHECKING_ACCOUNT = 'CCTE',
  LOW_AMOUNT_DEPOSIT = 'DBMO',
  ORDINARY_DEPOSIT = 'DORD',
  INCLUSIVE_LOW_AMOUNT_DEPOSIT = 'DBMI'
}

export enum PersonTypeDife {
  NATURAL_PERSON = 'N',
  LEGAL_PERSON = 'L'
}

export enum SpbviReceptorDife {
  CREDIBANCO = 'CRB',
  TRANSFIYA = 'TFY',
  BETWEEN_ACCOUNTS = 'ENT',
  VISIONAMOS = 'VIS',
  SERVIBANCA = 'SRV'
}
